DESTINATION_SEEDS: tuple[dict, ...] = (
    {
        "id": "dest_kuta_beach",
        "name": "Pantai Kuta",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai populer untuk sunset, belajar selancar, dan kuliner tepi laut.",
        "estimated_cost_idr": 150000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Kuta Bali",
        "google_place_id": "ChIJQw23KrxG0i0RjrRKL-Gq_oI",
    },
    {
        "id": "dest_tanjung_tinggi",
        "name": "Pantai Tanjung Tinggi",
        "categories": ["pantai"],
        "region": "Belitung",
        "description": "Pantai berpasir putih dengan batu granit besar dan air jernih.",
        "estimated_cost_idr": 120000,
        "suggested_duration_hours": 5,
        "search_query": "Pantai Tanjung Tinggi Belitung",
        "google_place_id": "ChIJ7xWNfTVCFy4Rz6cppS6tm9A",
    },
    {
        "id": "dest_pink_beach_komodo",
        "name": "Pink Beach Komodo",
        "categories": ["pantai"],
        "region": "Nusa Tenggara Timur",
        "description": "Pantai merah muda di kawasan Komodo untuk snorkeling dan panorama pulau.",
        "estimated_cost_idr": 450000,
        "suggested_duration_hours": 5,
        "search_query": "Pink Beach Komodo National Park",
        "google_place_id": "ChIJZxm99nxWtC0R0F8cpay0Lp8",
    },
    {
        "id": "dest_parangtritis",
        "name": "Pantai Parangtritis",
        "categories": ["pantai"],
        "region": "Yogyakarta",
        "description": "Pantai selatan ikonik dengan gumuk pasir, ombak besar, dan suasana senja.",
        "estimated_cost_idr": 100000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Parangtritis Yogyakarta",
        "google_place_id": "ChIJPVOsXpcAey4RNi7iUxT-GzU",
    },
    {
        "id": "dest_pandawa",
        "name": "Pantai Pandawa",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai bertebing kapur dengan air tenang untuk berenang dan kayak.",
        "estimated_cost_idr": 170000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Pandawa Bali",
        "google_place_id": "ChIJMR-62Hxb0i0RpLJV0F14uEE",
    },
    {
        "id": "dest_melasti_ungasan",
        "name": "Pantai Melasti Ungasan",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai tebing dramatis di Ungasan dengan akses jalan berliku dan sunset luas.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Melasti Ungasan Bali",
        "google_place_id": "ChIJf6d0f5Nb0i0Rq_tEZeZB_Nc",
    },
    {
        "id": "dest_sanur",
        "name": "Pantai Sanur",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai pagi yang tenang dengan promenade, sunrise, dan perahu tradisional.",
        "estimated_cost_idr": 140000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Sanur Bali",
        "google_place_id": "ChIJwRIJzsFB0i0RQdXwd3GvJvA",
    },
    {
        "id": "dest_nusa_dua",
        "name": "Pantai Nusa Dua",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai resor dengan pasir rapi, air relatif tenang, dan fasilitas nyaman.",
        "estimated_cost_idr": 220000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Nusa Dua Bali",
        "google_place_id": "ChIJ36guPCFD0i0Rjy6h57qPm_4",
    },
    {
        "id": "dest_ora",
        "name": "Pantai Ora",
        "categories": ["pantai"],
        "region": "Maluku",
        "description": "Pantai terpencil dengan air jernih dan suasana pulau yang tenang.",
        "estimated_cost_idr": 650000,
        "suggested_duration_hours": 6,
        "search_query": "Pantai Ora Maluku",
        "google_place_id": "ChIJq6qqqqo6ai0Ra0aQIZS76fg",
    },
    {
        "id": "dest_papuma",
        "name": "Pantai Papuma",
        "categories": ["pantai"],
        "region": "Jawa Timur",
        "description": "Pantai Jember dengan batu karang besar, bukit pandang, dan panorama laut selatan.",
        "estimated_cost_idr": 160000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Papuma Jember",
        "google_place_id": "ChIJjc21pKaC1i0RLi2eoPNCwrk",
    },
    {
        "id": "dest_bromo",
        "name": "Gunung Bromo",
        "categories": ["gunung"],
        "region": "Jawa Timur",
        "description": "Kawasan pegunungan vulkanik dengan sunrise, lautan pasir, dan bukit pandang.",
        "estimated_cost_idr": 450000,
        "suggested_duration_hours": 10,
        "search_query": "Gunung Bromo Jawa Timur",
        "google_place_id": "ChIJQUp5q6o31i0R3aXS7DYNpK0",
    },
    {
        "id": "dest_rinjani",
        "name": "Gunung Rinjani",
        "categories": ["gunung"],
        "region": "Lombok",
        "description": "Destinasi pendakian ikonik dengan panorama Danau Segara Anak.",
        "estimated_cost_idr": 1200000,
        "suggested_duration_hours": 48,
        "search_query": "Gunung Rinjani Lombok",
        "google_place_id": "ChIJz8wWAoAtzC0RHgrTEb_NAzw",
    },
    {
        "id": "dest_kawah_ijen",
        "name": "Kawah Ijen",
        "categories": ["gunung"],
        "region": "Jawa Timur",
        "description": "Kawah vulkanik dengan danau asam, jalur mendaki malam, dan fenomena blue fire.",
        "estimated_cost_idr": 500000,
        "suggested_duration_hours": 8,
        "search_query": "Kawah Ijen Banyuwangi",
        "google_place_id": "ChIJB-YKEfJJ0S0RvDlenQLvBHw",
    },
    {
        "id": "dest_merapi",
        "name": "Gunung Merapi",
        "categories": ["gunung"],
        "region": "Yogyakarta",
        "description": "Gunung aktif dengan lanskap lava, desa wisata, dan rute jeep di lerengnya.",
        "estimated_cost_idr": 350000,
        "suggested_duration_hours": 6,
        "search_query": "Gunung Merapi Yogyakarta",
        "google_place_id": "ChIJpS__wB5kei4RAIitTGISJuk",
    },
    {
        "id": "dest_prau",
        "name": "Gunung Prau",
        "categories": ["gunung"],
        "region": "Jawa Tengah",
        "description": "Pendakian relatif singkat di Dieng dengan sunrise dan bukit savana.",
        "estimated_cost_idr": 300000,
        "suggested_duration_hours": 12,
        "search_query": "Gunung Prau Dieng",
        "google_place_id": "ChIJEarWNyENcC4RAat0vCUOm4k",
    },
    {
        "id": "dest_semeru",
        "name": "Gunung Semeru",
        "categories": ["gunung"],
        "region": "Jawa Timur",
        "description": "Gunung tertinggi di Jawa dengan rute panjang, Ranu Kumbolo, dan lanskap vulkanik.",
        "estimated_cost_idr": 1000000,
        "suggested_duration_hours": 48,
        "search_query": "Gunung Semeru Jawa Timur",
        "google_place_id": "ChIJuxfY4Yk-1i0RVI9IPO3UFJw",
    },
    {
        "id": "dest_papandayan",
        "name": "Gunung Papandayan",
        "categories": ["gunung"],
        "region": "Jawa Barat",
        "description": "Kawah, hutan mati, dan area camping yang cocok untuk pendaki pemula.",
        "estimated_cost_idr": 380000,
        "suggested_duration_hours": 10,
        "search_query": "Gunung Papandayan Garut",
        "google_place_id": "ChIJEw3vL9mjaC4RdnfjmT3x_jI",
    },
    {
        "id": "dest_kerinci",
        "name": "Gunung Kerinci",
        "categories": ["gunung"],
        "region": "Jambi",
        "description": "Pendakian tinggi di Sumatra dengan hutan tropis dan panorama Taman Nasional Kerinci Seblat.",
        "estimated_cost_idr": 1150000,
        "suggested_duration_hours": 48,
        "search_query": "Gunung Kerinci Summit Kerinci Jambi",
        "google_place_id": "ChIJhWK-d2n5LC4RaflHgRtJ_qQ",
    },
    {
        "id": "dest_batur",
        "name": "Gunung Batur",
        "categories": ["gunung"],
        "region": "Bali",
        "description": "Pendakian sunrise populer di Kintamani dengan pemandangan danau dan kaldera.",
        "estimated_cost_idr": 450000,
        "suggested_duration_hours": 6,
        "search_query": "Gunung Batur Bali",
        "google_place_id": "ChIJP-7oyAP00S0RtHCGoa9FgNM",
    },
    {
        "id": "dest_kelimutu",
        "name": "Gunung Kelimutu",
        "categories": ["gunung"],
        "region": "Nusa Tenggara Timur",
        "description": "Gunung dengan tiga danau kawah berwarna dan sunrise di Flores.",
        "estimated_cost_idr": 500000,
        "suggested_duration_hours": 8,
        "search_query": "Gunung Kelimutu Flores",
        "google_place_id": "ChIJh3pOKiBDrS0RQXUqPqNWPaI",
    },
    {
        "id": "dest_tumpak_sewu",
        "name": "Air Terjun Tumpak Sewu",
        "categories": ["air_terjun"],
        "region": "Jawa Timur",
        "description": "Air terjun bertingkat lebar dengan jalur trekking dan panorama tebing.",
        "estimated_cost_idr": 200000,
        "suggested_duration_hours": 5,
        "search_query": "Air Terjun Tumpak Sewu",
        "google_place_id": "ChIJQdppWAgU1i0Rgil3Bl_MlEo",
    },
    {
        "id": "dest_madakaripura",
        "name": "Air Terjun Madakaripura",
        "categories": ["air_terjun"],
        "region": "Jawa Timur",
        "description": "Air terjun tinggi di lembah sempit dekat kawasan Bromo.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Air Terjun Madakaripura",
        "google_place_id": "ChIJEVDUNIFK1i0RIzh6_9vIFI0",
    },
    {
        "id": "dest_sekumpul",
        "name": "Air Terjun Sekumpul",
        "categories": ["air_terjun"],
        "region": "Bali",
        "description": "Kompleks air terjun di Buleleng dengan jalur trekking desa dan lembah hijau.",
        "estimated_cost_idr": 250000,
        "suggested_duration_hours": 5,
        "search_query": "Air Terjun Sekumpul Bali",
        "google_place_id": "ChIJNyp2FiCP0S0RNamdBru46Bg",
    },
    {
        "id": "dest_gitgit",
        "name": "Air Terjun Gitgit",
        "categories": ["air_terjun"],
        "region": "Bali",
        "description": "Air terjun mudah dijangkau di Bali utara dengan jalur pendek dan suasana hutan.",
        "estimated_cost_idr": 160000,
        "suggested_duration_hours": 3,
        "search_query": "Air Terjun Gitgit Bali",
        "google_place_id": "ChIJ2bn7v86P0S0RQNlEPMKB6JU",
    },
    {
        "id": "dest_sipiso_piso",
        "name": "Air Terjun Sipiso Piso",
        "categories": ["air_terjun"],
        "region": "Sumatera Utara",
        "description": "Air terjun tinggi dekat Danau Toba dengan titik pandang luas.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Air Terjun Sipiso Piso Sumatera Utara",
        "google_place_id": "ChIJ6TGUtnCtMTARf_RpQIsNK40",
    },
    {
        "id": "dest_coban_rondo",
        "name": "Air Terjun Coban Rondo",
        "categories": ["air_terjun"],
        "region": "Jawa Timur",
        "description": "Air terjun pegunungan dekat Batu dengan area wisata keluarga dan udara sejuk.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Air Terjun Coban Rondo Batu Malang",
        "google_place_id": "ChIJL6yQmACHeC4RdCI-fZisRp8",
    },
    {
        "id": "dest_sri_gethuk",
        "name": "Air Terjun Sri Gethuk",
        "categories": ["air_terjun"],
        "region": "Yogyakarta",
        "description": "Air terjun di Gunungkidul dengan tebing kapur dan akses perahu sungai.",
        "estimated_cost_idr": 170000,
        "suggested_duration_hours": 4,
        "search_query": "Air Terjun Sri Gethuk Gunungkidul",
        "google_place_id": "ChIJ7b3_osVSei4R8Xsm6jYVsgE",
    },
    {
        "id": "dest_benang_kelambu",
        "name": "Air Terjun Benang Kelambu",
        "categories": ["air_terjun"],
        "region": "Lombok",
        "description": "Air terjun bertirai di kaki Rinjani dengan suasana hutan tropis.",
        "estimated_cost_idr": 220000,
        "suggested_duration_hours": 5,
        "search_query": "Air Terjun Benang Kelambu Lombok",
        "google_place_id": "ChIJ_____3vMzS0RpV-XoZGa9rw",
    },
    {
        "id": "dest_kanto_lampo",
        "name": "Air Terjun Kanto Lampo",
        "categories": ["air_terjun"],
        "region": "Bali",
        "description": "Air terjun bertingkat batu di Gianyar yang populer untuk foto dan bermain air.",
        "estimated_cost_idr": 160000,
        "suggested_duration_hours": 3,
        "search_query": "Air Terjun Kanto Lampo Bali",
        "google_place_id": "ChIJoQHcmv8X0i0RI6vXSuiyCOo",
    },
    {
        "id": "dest_curug_cimahi",
        "name": "Curug Cimahi",
        "categories": ["air_terjun"],
        "region": "Jawa Barat",
        "description": "Air terjun tinggi di Bandung Barat dengan jalur tangga dan panorama hutan.",
        "estimated_cost_idr": 150000,
        "suggested_duration_hours": 3,
        "search_query": "Curug Cimahi Bandung",
        "google_place_id": "ChIJc5yw4_fhaC4RhxOyVZWZifI",
    },
    {
        "id": "dest_borobudur",
        "name": "Candi Borobudur",
        "categories": ["wisata_tradisional"],
        "region": "Jawa Tengah",
        "description": "Warisan budaya Buddhis dengan relief, stupa, dan lanskap Magelang.",
        "estimated_cost_idr": 250000,
        "suggested_duration_hours": 4,
        "search_query": "Candi Borobudur Magelang",
        "google_place_id": "ChIJl9anCfCMei4Ry8NNdDRD0w0",
    },
    {
        "id": "dest_prambanan",
        "name": "Candi Prambanan",
        "categories": ["wisata_tradisional"],
        "region": "Yogyakarta",
        "description": "Kompleks candi Hindu dengan relief Ramayana dan latar budaya Jawa.",
        "estimated_cost_idr": 240000,
        "suggested_duration_hours": 4,
        "search_query": "Candi Prambanan Yogyakarta",
        "google_place_id": "ChIJ0VnY2-Naei4RLVqVJTug5xk",
    },
    {
        "id": "dest_keraton_yogyakarta",
        "name": "Keraton Yogyakarta",
        "categories": ["wisata_tradisional"],
        "region": "Yogyakarta",
        "description": "Istana budaya Jawa dengan museum, arsitektur keraton, dan tradisi kerajaan.",
        "estimated_cost_idr": 160000,
        "suggested_duration_hours": 3,
        "search_query": "Keraton Yogyakarta",
        "google_place_id": "ChIJ78cG25ZXei4RbCcrBc9xUjk",
    },
    {
        "id": "dest_taman_sari",
        "name": "Taman Sari Yogyakarta",
        "categories": ["wisata_tradisional"],
        "region": "Yogyakarta",
        "description": "Bekas taman kerajaan dengan lorong, kolam, dan kampung bersejarah.",
        "estimated_cost_idr": 130000,
        "suggested_duration_hours": 3,
        "search_query": "Taman Sari Yogyakarta",
        "google_place_id": "ChIJK8_C0JNXei4RE74coPghaic",
    },
    {
        "id": "dest_penglipuran",
        "name": "Desa Adat Penglipuran",
        "categories": ["wisata_tradisional"],
        "region": "Bali",
        "description": "Desa adat Bali dengan tata ruang rapi, rumah tradisional, dan budaya lokal.",
        "estimated_cost_idr": 200000,
        "suggested_duration_hours": 4,
        "search_query": "Desa Adat Penglipuran Bali",
        "google_place_id": "ChIJqfTkrG4Z0i0RGTQM35oWGTM",
    },
    {
        "id": "dest_ubud_palace",
        "name": "Puri Saren Agung Ubud",
        "categories": ["wisata_tradisional"],
        "region": "Bali",
        "description": "Puri tradisional di pusat Ubud dengan arsitektur Bali dan pertunjukan budaya.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 3,
        "search_query": "Puri Saren Agung Ubud Bali",
        "google_place_id": "ChIJay5BfGE90i0RME7jGwpLp4g",
    },
    {
        "id": "dest_kete_kesu",
        "name": "Tongkonan Kete Kesu",
        "categories": ["wisata_tradisional"],
        "region": "Sulawesi Selatan",
        "description": "Kawasan tongkonan Toraja dengan rumah adat, ukiran, dan situs budaya.",
        "estimated_cost_idr": 260000,
        "suggested_duration_hours": 4,
        "search_query": "Objek Wisata Kete Kesu Toraja",
        "google_place_id": "ChIJqT4iSqHpky0RKXyR5A7BxFk",
    },
    {
        "id": "dest_kampung_naga",
        "name": "Kampung Naga",
        "categories": ["wisata_tradisional"],
        "region": "Jawa Barat",
        "description": "Kampung adat Sunda dengan lanskap lembah dan tata hidup tradisional.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Kampung Naga Tasikmalaya",
        "google_place_id": "ChIJgXM-U4GraC4R6TNrs7DX06o",
    },
    {
        "id": "dest_wae_rebo",
        "name": "Desa Wae Rebo",
        "categories": ["wisata_tradisional"],
        "region": "Nusa Tenggara Timur",
        "description": "Desa tradisional di pegunungan Flores dengan rumah Mbaru Niang.",
        "estimated_cost_idr": 700000,
        "suggested_duration_hours": 24,
        "search_query": "Desa Wae Rebo Flores",
        "google_place_id": "ChIJnQ7osllksy0RiIrLfbjGdM4",
    },
    {
        "id": "dest_besakih",
        "name": "Pura Besakih",
        "categories": ["wisata_tradisional"],
        "region": "Bali",
        "description": "Kompleks pura terbesar di Bali di lereng Gunung Agung.",
        "estimated_cost_idr": 220000,
        "suggested_duration_hours": 4,
        "search_query": "Pura Besakih Bali",
        "google_place_id": "ChIJt7JIN74c0i0RSrvRjHk5_As",
    },
)
