DESTINATION_SEEDS: tuple[dict, ...] = (
    {
        "id": "dest_kuta_beach",
        "name": "Pantai Kuta",
        "categories": ["pantai"],
        "region": "Bali",
        "description": "Pantai populer untuk sunset, belajar selancar, dan kuliner tepi laut.",
        "estimated_cost_idr": 150000,
        "suggested_duration_hours": 4,
        "search_query": "Pantai Kuta Bali",
        "google_place_id": None,
    },
    {
        "id": "dest_tanjung_tinggi",
        "name": "Pantai Tanjung Tinggi",
        "categories": ["pantai"],
        "region": "Belitung",
        "description": "Pantai berpasir putih dengan batu granit besar dan air jernih.",
        "estimated_cost_idr": 120000,
        "suggested_duration_hours": 5,
        "search_query": "Pantai Tanjung Tinggi Belitung",
        "google_place_id": None,
    },
    {
        "id": "dest_bromo",
        "name": "Gunung Bromo",
        "categories": ["gunung"],
        "region": "Jawa Timur",
        "description": "Kawasan pegunungan vulkanik dengan sunrise, lautan pasir, dan bukit pandang.",
        "estimated_cost_idr": 450000,
        "suggested_duration_hours": 10,
        "search_query": "Gunung Bromo Jawa Timur",
        "google_place_id": None,
    },
    {
        "id": "dest_rinjani",
        "name": "Gunung Rinjani",
        "categories": ["gunung"],
        "region": "Lombok",
        "description": "Destinasi pendakian ikonik dengan panorama Danau Segara Anak.",
        "estimated_cost_idr": 1200000,
        "suggested_duration_hours": 48,
        "search_query": "Gunung Rinjani Lombok",
        "google_place_id": None,
    },
    {
        "id": "dest_tumpak_sewu",
        "name": "Air Terjun Tumpak Sewu",
        "categories": ["air_terjun"],
        "region": "Jawa Timur",
        "description": "Air terjun bertingkat lebar dengan jalur trekking dan panorama tebing.",
        "estimated_cost_idr": 200000,
        "suggested_duration_hours": 5,
        "search_query": "Air Terjun Tumpak Sewu",
        "google_place_id": None,
    },
    {
        "id": "dest_madakaripura",
        "name": "Air Terjun Madakaripura",
        "categories": ["air_terjun"],
        "region": "Jawa Timur",
        "description": "Air terjun tinggi di lembah sempit dekat kawasan Bromo.",
        "estimated_cost_idr": 180000,
        "suggested_duration_hours": 4,
        "search_query": "Air Terjun Madakaripura",
        "google_place_id": None,
    },
    {
        "id": "dest_borobudur",
        "name": "Candi Borobudur",
        "categories": ["wisata_tradisional"],
        "region": "Jawa Tengah",
        "description": "Warisan budaya Buddhis dengan relief, stupa, dan lanskap Magelang.",
        "estimated_cost_idr": 250000,
        "suggested_duration_hours": 4,
        "search_query": "Candi Borobudur Magelang",
        "google_place_id": None,
    },
    {
        "id": "dest_tana_toraja",
        "name": "Tana Toraja",
        "categories": ["wisata_tradisional"],
        "region": "Sulawesi Selatan",
        "description": "Kawasan budaya dengan tongkonan, situs pemakaman batu, dan tradisi lokal.",
        "estimated_cost_idr": 650000,
        "suggested_duration_hours": 24,
        "search_query": "Tana Toraja Sulawesi Selatan",
        "google_place_id": None,
    },
)
