from sqlmodel import Session, select

from backend.app.db.models import Destination


DESTINATION_SEEDS = [
    {
        "id": "dest_001",
        "name": "Tebing Keraton",
        "city": "Bandung",
        "categories": ["alam", "gunung", "city_view"],
        "description": "Destinasi alam dengan pemandangan tebing dan hutan.",
        "address": "Ciburial, Bandung, Jawa Barat",
        "latitude": -6.8343,
        "longitude": 107.6631,
        "rating": 4.5,
        "review_count": 1200,
        "estimated_price": 25000,
        "average_visit_duration_minutes": 90,
        "opening_hours": {"raw": "05.00-18.00", "is_estimated": True},
    },
    {
        "id": "dest_002",
        "name": "Kawah Putih",
        "city": "Bandung",
        "categories": ["alam", "gunung"],
        "description": "Danau kawah vulkanik dengan lanskap putih kehijauan.",
        "address": "Ciwidey, Bandung, Jawa Barat",
        "latitude": -7.1662,
        "longitude": 107.4021,
        "rating": 4.6,
        "review_count": 1800,
        "estimated_price": 55000,
        "average_visit_duration_minutes": 120,
        "opening_hours": {"raw": "07.00-17.00", "is_estimated": True},
    },
    {
        "id": "dest_003",
        "name": "Farmhouse Lembang",
        "city": "Bandung",
        "categories": ["taman", "budaya", "kuliner"],
        "description": "Area wisata keluarga bergaya Eropa dengan spot foto dan kuliner.",
        "address": "Lembang, Bandung Barat, Jawa Barat",
        "latitude": -6.8329,
        "longitude": 107.6058,
        "rating": 4.4,
        "review_count": 2100,
        "estimated_price": 35000,
        "average_visit_duration_minutes": 120,
        "opening_hours": {"raw": "09.00-18.00", "is_estimated": True},
    },
    {
        "id": "dest_004",
        "name": "Dusun Bambu",
        "city": "Bandung",
        "categories": ["alam", "resort", "kuliner"],
        "description": "Resort dan taman rekreasi dengan restoran serta area danau.",
        "address": "Cisarua, Bandung Barat, Jawa Barat",
        "latitude": -6.7899,
        "longitude": 107.5789,
        "rating": 4.5,
        "review_count": 1600,
        "estimated_price": 30000,
        "average_visit_duration_minutes": 150,
        "opening_hours": {"raw": "10.00-20.00", "is_estimated": True},
    },
    {
        "id": "dest_005",
        "name": "Museum Geologi Bandung",
        "city": "Bandung",
        "categories": ["museum", "budaya"],
        "description": "Museum edukasi geologi dengan koleksi fosil, batuan, dan sejarah bumi.",
        "address": "Diponegoro, Bandung, Jawa Barat",
        "latitude": -6.9006,
        "longitude": 107.6215,
        "rating": 4.6,
        "review_count": 1500,
        "estimated_price": 10000,
        "average_visit_duration_minutes": 90,
        "opening_hours": {"raw": "09.00-15.00", "is_estimated": True},
    },
    {
        "id": "dest_006",
        "name": "Saung Angklung Udjo",
        "city": "Bandung",
        "categories": ["budaya", "museum"],
        "description": "Pusat pertunjukan dan edukasi angklung khas Sunda.",
        "address": "Padasuka, Bandung, Jawa Barat",
        "latitude": -6.8975,
        "longitude": 107.6547,
        "rating": 4.7,
        "review_count": 1300,
        "estimated_price": 75000,
        "average_visit_duration_minutes": 120,
        "opening_hours": {"raw": "08.00-17.00", "is_estimated": True},
    },
    {
        "id": "dest_007",
        "name": "Dago Dreampark",
        "city": "Bandung",
        "categories": ["taman", "alam", "city_view"],
        "description": "Taman rekreasi outdoor dengan wahana dan spot foto.",
        "address": "Dago Giri, Bandung Barat, Jawa Barat",
        "latitude": -6.8485,
        "longitude": 107.6235,
        "rating": 4.3,
        "review_count": 1750,
        "estimated_price": 40000,
        "average_visit_duration_minutes": 150,
        "opening_hours": {"raw": "09.00-17.00", "is_estimated": True},
    },
    {
        "id": "dest_008",
        "name": "Braga",
        "city": "Bandung",
        "categories": ["cafe", "budaya", "kuliner"],
        "description": "Koridor kota bersejarah dengan cafe, galeri, dan bangunan heritage.",
        "address": "Jalan Braga, Bandung, Jawa Barat",
        "latitude": -6.9175,
        "longitude": 107.6098,
        "rating": 4.5,
        "review_count": 2200,
        "estimated_price": 0,
        "average_visit_duration_minutes": 120,
        "opening_hours": {"raw": "24 jam area publik", "is_estimated": True},
    },
    {
        "id": "dest_009",
        "name": "Ranca Upas",
        "city": "Bandung",
        "categories": ["alam", "resort", "taman"],
        "description": "Area bumi perkemahan dan konservasi rusa di kawasan Ciwidey.",
        "address": "Ciwidey, Bandung, Jawa Barat",
        "latitude": -7.1388,
        "longitude": 107.3939,
        "rating": 4.5,
        "review_count": 1900,
        "estimated_price": 25000,
        "average_visit_duration_minutes": 150,
        "opening_hours": {"raw": "07.00-17.00", "is_estimated": True},
    },
    {
        "id": "dest_010",
        "name": "Orchid Forest Cikole",
        "city": "Bandung",
        "categories": ["alam", "taman", "resort"],
        "description": "Hutan pinus dan taman anggrek dengan jalur jalan kaki dan area foto.",
        "address": "Cikole, Lembang, Bandung Barat, Jawa Barat",
        "latitude": -6.7807,
        "longitude": 107.6379,
        "rating": 4.6,
        "review_count": 1700,
        "estimated_price": 50000,
        "average_visit_duration_minutes": 150,
        "opening_hours": {"raw": "09.00-18.00", "is_estimated": True},
    },
]


def seed_destinations(session: Session) -> None:
    existing = session.exec(select(Destination.id).limit(1)).first()
    if existing:
        return

    for item in DESTINATION_SEEDS:
        session.add(Destination(**item))
    session.commit()
